// packages/react/src/components/connect-button.tsx
import {
  type FlowState,
  type PlatformInfo,
  type WalletListEntry,
} from '@monolithlabs-hub/wallet-connect-core'
import {
  attachModal,
  getDialogAttributes,
  getStatusBadge,
  getWalletStatus,
  truncatePublicKey,
  type StatusBadge,
  type WalletStatus,
} from '@monolithlabs-hub/wallet-connect-ui'
import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react'

import { useWallet } from '../hooks/use-wallet'

/**
 * Props for {@link ConnectButton}.
 */
export interface ConnectButtonProps {
  /** Label on the button when disconnected. Default: `"Connect Wallet"`. */
  label?: string
  /**
   * Fallback label on the button when the flow is in a `connected` /
   * `signing` / `authenticated` state but no public key is available to
   * truncate. In practice the FlowMachine sets `publicKey` before
   * transitioning to `connected`, so the visible label is normally the
   * truncated key — this prop is the safety net for that invariant.
   * Default: `"Connected"`.
   */
  connectedLabel?: string
  className?: string
  style?: CSSProperties
  /** Fires once when the connect flow completes successfully. */
  onConnected?: (publicKey: string) => void
  /**
   * Fires once when SIWS sign-in completes successfully. Only fires for
   * managers configured with `requireSignIn: true`.
   */
  onAuthenticated?: (publicKey: string, signature: string) => void
}

const DEFAULT_LABEL = 'Connect Wallet'
const DEFAULT_CONNECTED_LABEL = 'Connected'
const PINNED_WALLET_ID = 'opindex'

function isFlowStateConnected(state: FlowState): boolean {
  return state === 'connected' || state === 'signing' || state === 'authenticated'
}

/**
 * Per-row badge decision. The wallet-list never renders the connected
 * row (the parent swaps to ConnectedView on `isConnected`), so the
 * `connected` status branch is unreachable here — left in for clarity.
 *
 * Returns `null` to suppress the badge entirely for non-pinned wallets
 * that aren't detected (those rows render as plain rows with no prompt).
 * The pinned wallet always carries either a "Detected" or "Get"/"Install"
 * badge depending on whether its extension is registered.
 */
function badgeForRow(wallet: WalletListEntry, platform: PlatformInfo): StatusBadge | null {
  const status: WalletStatus = getWalletStatus({
    isConnected: false,
    isDetected: wallet.isDetected,
  })
  const effective = status === 'install' && wallet.id !== PINNED_WALLET_ID ? null : status
  if (effective === null) return null
  return getStatusBadge({ status: effective, isIOS: platform.isIOS })
}

function initialFor(name: string): string {
  const trimmed = name.trim()
  if (trimmed.length === 0) return '?'
  return trimmed.charAt(0).toUpperCase()
}

/**
 * Ready-to-use button that runs the full wallet connect flow.
 *
 * - Disconnected: shows `label` ("Connect Wallet" by default). Clicking
 *   opens a modal listing the manager's sorted wallets. The pinned
 *   wallet carries a "Get" badge on iOS (App Store convention) and an
 *   "Install" badge on Android / desktop without the Opindex extension.
 * - Connected: the button shows a truncated public key. Clicking opens
 *   the modal in "connected" mode with a Disconnect action.
 *
 * Modal accessibility, focus management, and body scroll lock are
 * handled by `@monolithlabs-hub/wallet-connect-ui`'s {@link attachModal} —
 * see `WalletModal` below for the integration.
 */
export function ConnectButton({
  label = DEFAULT_LABEL,
  connectedLabel = DEFAULT_CONNECTED_LABEL,
  className,
  style,
  onConnected,
  onAuthenticated,
}: ConnectButtonProps): ReactNode {
  const wallet = useWallet()
  const [open, setOpen] = useState(false)
  // Platform comes from the manager — it reflects BOTH the legacy
  // `window.opindex` sentinel AND the Wallet Standard registry so
  // late-registering Opindex flips `hasOpindexExtension` automatically.
  const platform = wallet.platform

  const titleId = useId()

  // Fire `onConnected` / `onAuthenticated` on flow-state transitions.
  // Auto-closes on the `authenticated` transition rather than `connected`
  // so requireSignIn flows keep the dialog visible through the signing
  // step (see TASK-203 review).
  const prevStateRef = useRef<FlowState>(wallet.state)
  useEffect(() => {
    const prev = prevStateRef.current
    const curr = wallet.state
    prevStateRef.current = curr

    const wasConnected = isFlowStateConnected(prev)
    const isNowConnected = isFlowStateConnected(curr)

    if (!wasConnected && isNowConnected && wallet.publicKey) {
      onConnected?.(wallet.publicKey)
    }

    if (prev !== 'authenticated' && curr === 'authenticated') {
      if (wallet.publicKey && wallet.signature) {
        onAuthenticated?.(wallet.publicKey, wallet.signature)
      }
      setOpen(false)
    }
  }, [wallet.state, wallet.publicKey, wallet.signature, onConnected, onAuthenticated])

  // Pass the walletId straight into `wallet.connect` — bypasses the React
  // state cycle (no need for `select()` first).
  const walletConnect = wallet.connect
  const handleSelectWallet = useCallback(
    async (walletId: string) => {
      try {
        await walletConnect(walletId)
      } catch {
        // Errors land on `wallet.error`; the modal renders that branch.
      }
    },
    [walletConnect],
  )

  const walletDisconnect = wallet.disconnect
  const handleDisconnect = useCallback(async () => {
    try {
      await walletDisconnect()
    } catch {
      // Best-effort. The FlowMachine RESET runs unconditionally.
    }
    setOpen(false)
  }, [walletDisconnect])

  const truncated = wallet.publicKey ? truncatePublicKey(wallet.publicKey) : null
  // Connected for display purposes — the flow has entered the
  // `connected | signing | authenticated` cluster. Public key may not yet
  // be set in the (rare) instant before `WALLET_CONNECTED` lands; the
  // `connectedLabel` fallback covers that case.
  const isConnected = isFlowStateConnected(wallet.state)

  const buttonLabel = isConnected ? (truncated ?? connectedLabel) : label
  const buttonAriaLabel = isConnected
    ? `Wallet menu — connected as ${truncated ?? 'unknown'}`
    : label

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-haspopup="dialog"
        aria-expanded={open}
        aria-label={buttonAriaLabel}
        className={className}
        style={style}
      >
        {buttonLabel}
      </button>
      {open ? (
        <WalletModal
          titleId={titleId}
          title={isConnected ? 'Connected' : 'Select a wallet'}
          onClose={() => setOpen(false)}
        >
          {isConnected ? (
            <ConnectedView
              publicKey={wallet.publicKey ?? ''}
              walletName={wallet.wallet?.name ?? null}
              onDisconnect={handleDisconnect}
              disconnecting={wallet.disconnecting}
            />
          ) : (
            <WalletList
              wallets={wallet.sortedWallets}
              platform={platform}
              state={wallet.state}
              connectingWalletId={wallet.wallet?.id ?? null}
              errorMessage={wallet.error?.message ?? null}
              onSelect={handleSelectWallet}
            />
          )}
        </WalletModal>
      ) : null}
    </>
  )
}

// ---------------------------------------------------------------------------
// Internal rendering helpers. Lifecycle / a11y wiring delegated to
// `@monolithlabs-hub/wallet-connect-ui` (TASK-401); this file only owns the JSX
// shape and the inline default styling.
// ---------------------------------------------------------------------------

interface WalletModalProps {
  titleId: string
  title: string
  onClose: () => void
  children: ReactNode
}

function WalletModal({ titleId, title, onClose, children }: WalletModalProps): ReactNode {
  const dialogRef = useRef<HTMLDivElement>(null)
  // Stabilize the close callback via a ref so attaching `attachModal`
  // doesn't re-fire when the parent re-renders with a fresh inline
  // closure. The ref is updated in a useEffect (not during render) to
  // satisfy `react-hooks/refs`. Timing: between render and effect the
  // ref points at the previous closure — fine for our case since both
  // resolve to `() => setOpen(false)` and setOpen is stable.
  const onCloseRef = useRef(onClose)
  useEffect(() => {
    onCloseRef.current = onClose
  }, [onClose])

  useEffect(() => {
    const dialog = dialogRef.current
    if (!dialog) return
    const handle = attachModal({
      root: dialog,
      onRequestClose: () => onCloseRef.current(),
    })
    return () => handle.destroy()
  }, [])

  return (
    <div
      role="presentation"
      style={modalBackdropStyle}
      onClick={(e) => {
        // Click on the backdrop (NOT a descendant) closes the modal.
        if (e.target === e.currentTarget) onCloseRef.current()
      }}
    >
      <div
        ref={dialogRef}
        {...getDialogAttributes(titleId)}
        data-wc-modal=""
        style={modalContentStyle}
      >
        <header style={modalHeaderStyle}>
          <h2 id={titleId} style={modalTitleStyle}>
            {title}
          </h2>
          <button
            type="button"
            onClick={() => onCloseRef.current()}
            aria-label="Close"
            data-wc-modal-close=""
            style={modalCloseButtonStyle}
          >
            {'×'}
          </button>
        </header>
        <div>{children}</div>
      </div>
    </div>
  )
}

interface WalletListProps {
  wallets: readonly WalletListEntry[]
  platform: PlatformInfo
  state: FlowState
  connectingWalletId: string | null
  errorMessage: string | null
  onSelect: (walletId: string) => void
}

function WalletList({
  wallets,
  platform,
  state,
  connectingWalletId,
  errorMessage,
  onSelect,
}: WalletListProps): ReactNode {
  if (wallets.length === 0) {
    return <p style={{ padding: '12px 16px', margin: 0 }}>No wallets configured.</p>
  }
  return (
    <ul role="list" style={walletListStyle}>
      {wallets.map((wallet) => {
        const badge = badgeForRow(wallet, platform)
        const isConnecting = state === 'connecting' && connectingWalletId === wallet.id
        return (
          <li key={wallet.id} style={{ margin: 0 }}>
            <button
              type="button"
              data-wallet-id={wallet.id}
              data-wc-wallet-item=""
              onClick={() => onSelect(wallet.id)}
              disabled={state === 'connecting' || state === 'signing'}
              style={walletItemButtonStyle}
            >
              {wallet.icon ? (
                <img src={wallet.icon} alt="" width={24} height={24} style={walletIconStyle} />
              ) : (
                <span aria-hidden="true" style={walletIconFallbackStyle}>
                  {initialFor(wallet.name)}
                </span>
              )}
              <span style={{ flex: 1, textAlign: 'left' }}>{wallet.name}</span>
              {isConnecting ? <span style={walletStatusStyle}>Connecting…</span> : null}
              {badge ? (
                <span style={badge === 'Detected' ? walletDetectedBadgeStyle : walletBadgeStyle}>
                  {badge}
                </span>
              ) : null}
            </button>
          </li>
        )
      })}
      {errorMessage ? (
        <li role="alert" style={errorRowStyle}>
          {errorMessage}
        </li>
      ) : null}
    </ul>
  )
}

interface ConnectedViewProps {
  publicKey: string
  walletName: string | null
  disconnecting: boolean
  onDisconnect: () => void
}

function ConnectedView({
  publicKey,
  walletName,
  disconnecting,
  onDisconnect,
}: ConnectedViewProps): ReactNode {
  return (
    <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: 12 }}>
      {walletName ? <p style={{ margin: 0, fontWeight: 600 }}>{walletName}</p> : null}
      <p style={{ margin: 0, fontFamily: 'monospace', wordBreak: 'break-all' }}>{publicKey}</p>
      <button
        type="button"
        onClick={onDisconnect}
        disabled={disconnecting}
        style={disconnectButtonStyle}
      >
        {disconnecting ? 'Disconnecting…' : 'Disconnect'}
      </button>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Default styling. Every visual value reads from a CSS custom property
// (e.g., `var(--wc-bg, #fff)`) so consumers can theme by setting variables
// on `[role="dialog"]`, on `[data-wc-modal]`, on a parent element, or on
// `:root`. The `@monolithlabs-hub/wallet-connect-ui` package injects a small
// stylesheet with the variable defaults plus hover / focus-visible / disabled
// rules (which can't be expressed via inline `style`).
// ---------------------------------------------------------------------------

const modalBackdropStyle: CSSProperties = {
  position: 'fixed',
  inset: 0,
  background: 'var(--wc-backdrop, rgba(0, 0, 0, 0.5))',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1000,
}

const modalContentStyle: CSSProperties = {
  background: 'var(--wc-bg, #fff)',
  color: 'var(--wc-fg, #111)',
  borderRadius: 'var(--wc-radius, 12px)',
  minWidth: 320,
  maxWidth: 'min(420px, calc(100vw - 32px))',
  maxHeight: 'calc(100vh - 32px)',
  overflow: 'auto',
  boxShadow: 'var(--wc-shadow, 0 20px 40px rgba(0, 0, 0, 0.3))',
}

const modalHeaderStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '14px 18px',
  borderBottom: '1px solid var(--wc-border, rgba(0, 0, 0, 0.08))',
}

const modalTitleStyle: CSSProperties = {
  margin: 0,
  fontSize: 'var(--wc-title-size, 18px)',
  fontWeight: 600,
  letterSpacing: '-0.01em',
}

const modalCloseButtonStyle: CSSProperties = {
  background: 'transparent',
  border: 'none',
  fontSize: 22,
  lineHeight: 1,
  cursor: 'pointer',
  padding: 6,
  borderRadius: 'var(--wc-radius-item, 8px)',
  color: 'var(--wc-muted-fg, rgba(0, 0, 0, 0.6))',
}

const walletListStyle: CSSProperties = {
  listStyle: 'none',
  margin: 0,
  padding: 8,
  display: 'flex',
  flexDirection: 'column',
  gap: 2,
}

const walletItemButtonStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 12,
  width: '100%',
  padding: '10px 12px',
  background: 'transparent',
  border: 'none',
  borderRadius: 'var(--wc-radius-item, 8px)',
  cursor: 'pointer',
  font: 'inherit',
  color: 'inherit',
  textAlign: 'left',
}

const walletIconStyle: CSSProperties = {
  borderRadius: 6,
  display: 'block',
  flexShrink: 0,
}

const walletIconFallbackStyle: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  width: 24,
  height: 24,
  borderRadius: 6,
  background: 'var(--wc-badge-bg, rgba(0, 0, 0, 0.08))',
  color: 'var(--wc-muted-fg, rgba(0, 0, 0, 0.6))',
  fontSize: 12,
  fontWeight: 600,
  flexShrink: 0,
}

const walletBadgeStyle: CSSProperties = {
  fontSize: 12,
  fontWeight: 600,
  padding: '2px 8px',
  borderRadius: 999,
  background: 'var(--wc-badge-bg, rgba(0, 0, 0, 0.08))',
  color: 'var(--wc-badge-fg, inherit)',
}

const walletDetectedBadgeStyle: CSSProperties = {
  ...walletBadgeStyle,
  background: 'var(--wc-detected-bg, rgba(34, 197, 94, 0.12))',
  color: 'var(--wc-detected-fg, rgb(21, 128, 61))',
}

const walletStatusStyle: CSSProperties = {
  fontSize: 12,
  color: 'var(--wc-muted-fg, rgba(0, 0, 0, 0.6))',
}

const errorRowStyle: CSSProperties = {
  margin: '8px 12px 0',
  padding: '8px 12px',
  borderRadius: 'var(--wc-radius-item, 8px)',
  background: 'var(--wc-error-bg, rgba(220, 38, 38, 0.08))',
  color: 'var(--wc-error-fg, rgb(185, 28, 28))',
  fontSize: 13,
}

const disconnectButtonStyle: CSSProperties = {
  padding: '10px 14px',
  border: '1px solid var(--wc-border, rgba(0, 0, 0, 0.12))',
  borderRadius: 'var(--wc-radius-item, 8px)',
  background: 'transparent',
  cursor: 'pointer',
  font: 'inherit',
  color: 'inherit',
  fontWeight: 500,
}

// packages/vue/src/components/ConnectButton.vue
<script setup lang="ts">
import { type FlowState, type WalletListEntry } from '@monolithlabs-hub/wallet-connect-core'
import {
  attachModal,
  getDialogAttributes,
  getStatusBadge,
  getWalletStatus,
  truncatePublicKey,
  type ModalHandle,
  type StatusBadge,
  type WalletStatus,
} from '@monolithlabs-hub/wallet-connect-ui'
import {
  computed,
  nextTick,
  onUnmounted,
  ref,
  useId,
  useTemplateRef,
  watch,
  type CSSProperties,
} from 'vue'

import { useWallet } from '../composables/use-wallet'

/**
 * Ready-to-use Vue 3 component that runs the full wallet connect flow.
 *
 * Mirrors `@monolithlabs-hub/wallet-connect-react`'s `<ConnectButton>` in
 * behavior — same modal shell, focus trap, ARIA, and badge logic —
 * implemented as a Vue 3 single-file component using `<script setup>`.
 *
 * **Class / style forwarding**: Vue automatically forwards non-prop
 * attributes to the root element, so `<ConnectButton class="..." style="...">`
 * applies to the rendered `<button>` without needing explicit `class` /
 * `style` props. No `inheritAttrs: false` here.
 *
 * **Modal placement**: rendered into `document.body` via `<Teleport>` so
 * the modal isn't clipped by transformed ancestor containers (a common
 * footgun with `position: fixed` inside CSS-transformed parents).
 *
 * **Modal lifecycle** (focus trap, initial focus, focus restoration on
 * close, body scroll lock, Escape handler): delegated to
 * `@monolithlabs-hub/wallet-connect-ui`'s `attachModal`. This component owns
 * the JSX shape, the open/close state, and the inline default styling
 * only.
 */

const props = withDefaults(
  defineProps<{
    /** Label on the button when disconnected. Default: "Connect Wallet". */
    label?: string
    /**
     * Fallback label on the button when the flow is in a connected /
     * signing / authenticated state but no public key is available to
     * truncate. The FlowMachine sets publicKey before transitioning to
     * `connected`, so the visible label is normally the truncated key
     * — this is the safety net.
     */
    connectedLabel?: string
  }>(),
  {
    label: 'Connect Wallet',
    connectedLabel: 'Connected',
  },
)

const emit = defineEmits<{
  /** Fires once when the connect flow completes successfully. */
  connected: [publicKey: string]
  /**
   * Fires once when SIWS sign-in completes successfully. Only fires for
   * managers configured with `requireSignIn: true`.
   */
  authenticated: [publicKey: string, signature: string]
}>()

// Destructure the composable return so `<template>` can auto-unwrap the
// refs (Vue only auto-unwraps top-level refs — `wallet.publicKey` would
// stay wrapped, but `publicKey` doesn't). `wallet` is renamed to
// `activeWallet` to avoid shadowing the composable itself.
const {
  state,
  publicKey,
  signature,
  wallet: activeWallet,
  sortedWallets,
  platform,
  error,
  disconnecting,
  connect,
  disconnect,
} = useWallet()

const open = ref(false)
const titleId = useId()
const dialogRef = useTemplateRef<HTMLDivElement>('dialog')

const PINNED_WALLET_ID = 'opindex'

function isFlowStateConnected(state: FlowState): boolean {
  return state === 'connected' || state === 'signing' || state === 'authenticated'
}

/**
 * Per-row badge decision. Mirrors the React `<ConnectButton>` logic:
 * detected wallets get "Detected", the pinned wallet without an
 * extension gets "Get"/"Install", everything else gets nothing.
 */
function badgeFor(walletEntry: WalletListEntry): StatusBadge | null {
  const status: WalletStatus = getWalletStatus({
    isConnected: false,
    isDetected: walletEntry.isDetected,
  })
  const effective = status === 'install' && walletEntry.id !== PINNED_WALLET_ID ? null : status
  if (effective === null) return null
  return getStatusBadge({ status: effective, isIOS: platform.value.isIOS })
}

function initialFor(name: string): string {
  const trimmed = name.trim()
  if (trimmed.length === 0) return '?'
  return trimmed.charAt(0).toUpperCase()
}

const truncated = computed<string | null>(() =>
  publicKey.value ? truncatePublicKey(publicKey.value) : null,
)
const isConnected = computed(() => isFlowStateConnected(state.value))
const buttonLabel = computed(() =>
  isConnected.value ? (truncated.value ?? props.connectedLabel) : props.label,
)
const buttonAriaLabel = computed(() =>
  isConnected.value ? `Wallet menu — connected as ${truncated.value ?? 'unknown'}` : props.label,
)
const modalTitle = computed(() => (isConnected.value ? 'Connected' : 'Select a wallet'))
const walletItemsDisabled = computed(
  () => state.value === 'connecting' || state.value === 'signing',
)

// Transition watcher for `connected` / `authenticated` emits + auto-close.
//
// Auto-closes on the `authenticated` transition rather than on
// `connected`. For `requireSignIn: false` flows the FlowMachine
// auto-steps `connected → authenticated` in the same dispatch, so the
// close timing is unchanged. For `requireSignIn: true` flows the modal
// stays open through the `signing` state — the user keeps seeing the
// dialog while their wallet shows a sign prompt.
let prevState: FlowState = state.value
watch(state, (curr) => {
  const prev = prevState
  prevState = curr

  const wasConnected = isFlowStateConnected(prev)
  const isNowConnected = isFlowStateConnected(curr)

  if (!wasConnected && isNowConnected && publicKey.value) {
    emit('connected', publicKey.value)
  }

  if (prev !== 'authenticated' && curr === 'authenticated') {
    if (publicKey.value && signature.value) {
      emit('authenticated', publicKey.value, signature.value)
    }
    open.value = false
  }
})

async function handleSelectWallet(walletId: string): Promise<void> {
  try {
    await connect(walletId)
  } catch {
    // Errors land on `error`; the modal renders that branch.
  }
}

async function handleDisconnect(): Promise<void> {
  try {
    await disconnect()
  } catch {
    // Best-effort. The FlowMachine RESET runs unconditionally.
  }
  open.value = false
}

function handleBackdropClick(event: MouseEvent): void {
  if (event.target === event.currentTarget) {
    open.value = false
  }
}

// ---- Modal lifecycle (delegated to attachModal) ------------------------

let modalHandle: ModalHandle | null = null

watch(open, async (isOpen) => {
  if (isOpen) {
    // Wait for `<Teleport>` to commit so the dialog ref is populated
    // before attachModal queries it for focusables.
    await nextTick()
    if (dialogRef.value) {
      modalHandle = attachModal({
        root: dialogRef.value,
        onRequestClose: () => {
          open.value = false
        },
      })
    }
  } else {
    modalHandle?.destroy()
    modalHandle = null
  }
})

onUnmounted(() => {
  modalHandle?.destroy()
  modalHandle = null
})

const dialogAttrs = computed(() => getDialogAttributes(titleId))

// ---- Default styling --------------------------------------------------
// Every visual value reads from a CSS custom property (`var(--wc-foo,
// fallback)`) so consumers can theme via `[role="dialog"]`,
// `[data-wc-modal]`, a parent element, or `:root`. The
// `@monolithlabs-hub/wallet-connect-ui` package injects the variable
// defaults and the hover / focus-visible / disabled rules on first
// `attachModal` call.

const modalBackdropStyle: CSSProperties = {
  position: 'fixed',
  inset: '0',
  background: 'var(--wc-backdrop, rgba(0, 0, 0, 0.5))',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1000,
}

const modalContentStyle: CSSProperties = {
  background: 'var(--wc-bg, #fff)',
  color: 'var(--wc-fg, #111)',
  borderRadius: 'var(--wc-radius, 12px)',
  minWidth: '320px',
  maxWidth: 'min(420px, calc(100vw - 32px))',
  maxHeight: 'calc(100vh - 32px)',
  overflow: 'auto',
  boxShadow: 'var(--wc-shadow, 0 20px 40px rgba(0, 0, 0, 0.3))',
}

const modalHeaderStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '14px 18px',
  borderBottom: '1px solid var(--wc-border, rgba(0, 0, 0, 0.08))',
}

const modalTitleStyle: CSSProperties = {
  margin: '0',
  fontSize: 'var(--wc-title-size, 18px)',
  fontWeight: 600,
  letterSpacing: '-0.01em',
}

const modalCloseButtonStyle: CSSProperties = {
  background: 'transparent',
  border: 'none',
  fontSize: '22px',
  lineHeight: '1',
  cursor: 'pointer',
  padding: '6px',
  borderRadius: 'var(--wc-radius-item, 8px)',
  color: 'var(--wc-muted-fg, rgba(0, 0, 0, 0.6))',
}

const walletListStyle: CSSProperties = {
  listStyle: 'none',
  margin: '0',
  padding: '8px',
  display: 'flex',
  flexDirection: 'column',
  gap: '2px',
}

const walletItemButtonStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '12px',
  width: '100%',
  padding: '10px 12px',
  background: 'transparent',
  border: 'none',
  borderRadius: 'var(--wc-radius-item, 8px)',
  cursor: 'pointer',
  font: 'inherit',
  color: 'inherit',
  textAlign: 'left',
}

const walletIconStyle: CSSProperties = {
  borderRadius: '6px',
  display: 'block',
  flexShrink: 0,
}

const walletIconFallbackStyle: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  width: '24px',
  height: '24px',
  borderRadius: '6px',
  background: 'var(--wc-badge-bg, rgba(0, 0, 0, 0.08))',
  color: 'var(--wc-muted-fg, rgba(0, 0, 0, 0.6))',
  fontSize: '12px',
  fontWeight: 600,
  flexShrink: 0,
}

const walletBadgeStyle: CSSProperties = {
  fontSize: '12px',
  fontWeight: 600,
  padding: '2px 8px',
  borderRadius: '999px',
  background: 'var(--wc-badge-bg, rgba(0, 0, 0, 0.08))',
  color: 'var(--wc-badge-fg, inherit)',
}

const walletDetectedBadgeStyle: CSSProperties = {
  ...walletBadgeStyle,
  background: 'var(--wc-detected-bg, rgba(34, 197, 94, 0.12))',
  color: 'var(--wc-detected-fg, rgb(21, 128, 61))',
}

const walletStatusStyle: CSSProperties = {
  fontSize: '12px',
  color: 'var(--wc-muted-fg, rgba(0, 0, 0, 0.6))',
}

const errorRowStyle: CSSProperties = {
  margin: '8px 12px 0',
  padding: '8px 12px',
  borderRadius: 'var(--wc-radius-item, 8px)',
  background: 'var(--wc-error-bg, rgba(220, 38, 38, 0.08))',
  color: 'var(--wc-error-fg, rgb(185, 28, 28))',
  fontSize: '13px',
}

const disconnectButtonStyle: CSSProperties = {
  padding: '10px 14px',
  border: '1px solid var(--wc-border, rgba(0, 0, 0, 0.12))',
  borderRadius: 'var(--wc-radius-item, 8px)',
  background: 'transparent',
  cursor: 'pointer',
  font: 'inherit',
  color: 'inherit',
  fontWeight: 500,
}

const connectedViewStyle: CSSProperties = {
  padding: '14px 18px',
  display: 'flex',
  flexDirection: 'column',
  gap: '12px',
}
</script>

<template>
  <button
    type="button"
    aria-haspopup="dialog"
    :aria-expanded="open"
    :aria-label="buttonAriaLabel"
    @click="open = true"
  >
    {{ buttonLabel }}
  </button>

  <Teleport to="body">
    <div v-if="open" role="presentation" :style="modalBackdropStyle" @click="handleBackdropClick">
      <div ref="dialog" v-bind="dialogAttrs" data-wc-modal :style="modalContentStyle">
        <header :style="modalHeaderStyle">
          <h2 :id="titleId" :style="modalTitleStyle">{{ modalTitle }}</h2>
          <button
            type="button"
            aria-label="Close"
            data-wc-modal-close
            :style="modalCloseButtonStyle"
            @click="open = false"
          >
            ×
          </button>
        </header>
        <div>
          <!-- Connected view -->
          <div v-if="isConnected && publicKey" :style="connectedViewStyle">
            <p v-if="activeWallet" :style="{ margin: '0', fontWeight: 600 }">
              {{ activeWallet.name }}
            </p>
            <p :style="{ margin: '0', fontFamily: 'monospace', wordBreak: 'break-all' }">
              {{ publicKey }}
            </p>
            <button
              type="button"
              :disabled="disconnecting"
              :style="disconnectButtonStyle"
              @click="handleDisconnect"
            >
              {{ disconnecting ? 'Disconnecting…' : 'Disconnect' }}
            </button>
          </div>
          <!-- Wallet list -->
          <ul v-else-if="sortedWallets.length > 0" role="list" :style="walletListStyle">
            <li v-for="w in sortedWallets" :key="w.id" :style="{ margin: '0' }">
              <button
                type="button"
                :data-wallet-id="w.id"
                data-wc-wallet-item
                :disabled="walletItemsDisabled"
                :style="walletItemButtonStyle"
                @click="handleSelectWallet(w.id)"
              >
                <img
                  v-if="w.icon"
                  :src="w.icon"
                  alt=""
                  width="24"
                  height="24"
                  :style="walletIconStyle"
                />
                <span v-else aria-hidden="true" :style="walletIconFallbackStyle">
                  {{ initialFor(w.name) }}
                </span>
                <span :style="{ flex: 1, textAlign: 'left' }">{{ w.name }}</span>
                <span
                  v-if="state === 'connecting' && activeWallet?.id === w.id"
                  :style="walletStatusStyle"
                >
                  Connecting…
                </span>
                <span
                  v-if="badgeFor(w)"
                  :style="badgeFor(w) === 'Detected' ? walletDetectedBadgeStyle : walletBadgeStyle"
                >
                  {{ badgeFor(w) }}
                </span>
              </button>
            </li>
            <li v-if="error?.message" role="alert" :style="errorRowStyle">
              {{ error.message }}
            </li>
          </ul>
          <p v-else :style="{ padding: '12px 16px', margin: '0' }">No wallets configured.</p>
        </div>
      </div>
    </div>
  </Teleport>
</template>
